import React from 'react';
import { motion } from 'framer-motion';
import TestimonialCard from '@/components/landing/TestimonialCard';

const testimonials = [
  {
    quote: "Zer0Mind was instrumental in helping us refine our pitch and secure seed funding. The AI insights are game-changing!",
    author: "Alice Chen",
    role: "CEO, Innovatech Solutions",
    imageSrc: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
  },
  {
    quote: "As a solo founder, Zer0Mind feels like having an experienced co-founder by my side 24/7. Highly recommended!",
    author: "Marcus Bellwether",
    role: "Founder, EcoGrowth Startups",
    imageSrc: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
  },
  {
    quote: "The strategic roadmaps generated by the AI saved us months of planning. We launched ahead of schedule thanks to Zer0Mind.",
    author: "Sofia Ramirez",
    role: "CTO, QuantumLeap AI",
    imageSrc: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
  },
];

const TestimonialsSection = () => {
  return (
    <section className="w-full py-16 md:py-24">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary">
            Trusted by Founders Worldwide
          </h2>
          <p className="text-lg text-muted-foreground max-w-xl mx-auto">
            Hear what successful entrepreneurs are saying about Zer0Mind.
          </p>
        </motion.div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <TestimonialCard
              key={index}
              quote={testimonial.quote}
              author={testimonial.author}
              role={testimonial.role}
              imageSrc={testimonial.imageSrc}
              delay={index}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
